// Code generated by MockGen. DO NOT EDIT.
// Source: stt.go
//
// Generated by this command:
//
//	mockgen -source=stt.go -typed -package=mocks -destination=./mocks/stt_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/BobrePatre/grouse-backend/internal/message/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationSttGateway is a mock of NotificationSttGateway interface.
type MockNotificationSttGateway struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationSttGatewayMockRecorder
}

// MockNotificationSttGatewayMockRecorder is the mock recorder for MockNotificationSttGateway.
type MockNotificationSttGatewayMockRecorder struct {
	mock *MockNotificationSttGateway
}

// NewMockNotificationSttGateway creates a new mock instance.
func NewMockNotificationSttGateway(ctrl *gomock.Controller) *MockNotificationSttGateway {
	mock := &MockNotificationSttGateway{ctrl: ctrl}
	mock.recorder = &MockNotificationSttGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationSttGateway) EXPECT() *MockNotificationSttGatewayMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockNotificationSttGateway) Notify(ctx context.Context, notification *entity.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockNotificationSttGatewayMockRecorder) Notify(ctx, notification any) *MockNotificationSttGatewayNotifyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockNotificationSttGateway)(nil).Notify), ctx, notification)
	return &MockNotificationSttGatewayNotifyCall{Call: call}
}

// MockNotificationSttGatewayNotifyCall wrap *gomock.Call
type MockNotificationSttGatewayNotifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNotificationSttGatewayNotifyCall) Return(arg0 error) *MockNotificationSttGatewayNotifyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNotificationSttGatewayNotifyCall) Do(f func(context.Context, *entity.Message) error) *MockNotificationSttGatewayNotifyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNotificationSttGatewayNotifyCall) DoAndReturn(f func(context.Context, *entity.Message) error) *MockNotificationSttGatewayNotifyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
